services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=${KEYCLOAK_ADMIN_USER}
      - KC_BOOTSTRAP_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KEYCLOAK_FRONTEND_URL=${KEYCLOAK_HOST}
    volumes:
      - keycloak_data:/opt/keycloak/data
    command:
      - start-dev
      - --http-enabled=true
      - --proxy-headers=forwarded
      - --hostname=${KEYCLOAK_HOST}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak.entrypoints=websecure"
      - "traefik.http.routers.keycloak.rule=Host(`${KEYCLOAK_HOST}`)"
      - "traefik.http.routers.keycloak.tls.certresolver=myresolver"
      - "traefik.http.services.keycloak.loadbalancer.server.port=8080"
    networks:
      - traefik-net

volumes:
  keycloak_data:

networks:
  traefik-net:
    external: true